2020/06/11 17:35:03 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 17:35:04 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 17:41:32 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:41:32] "[32mGET /api/author HTTP/1.1[0m" 308 -
2020/06/11 17:41:32 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:41:32] "[35m[1mGET /api/author/ HTTP/1.1[0m" 500 -
2020/06/11 17:41:40 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:41:40] "[35m[1mGET /api/author/ HTTP/1.1[0m" 500 -
2020/06/11 17:44:46 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 17:44:51 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 17:44:59 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 17:45:00 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 17:57:02 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:57:02] "[32mGET /api/author HTTP/1.1[0m" 308 -
2020/06/11 17:57:02 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:57:02] "[35m[1mGET /api/author/ HTTP/1.1[0m" 500 -
2020/06/11 17:57:22 root __init__.py[98] not_found() ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2020/06/11 17:57:22 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:57:22] "[33mGET /api/book HTTP/1.1[0m" 404 -
2020/06/11 17:57:27 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:57:27] "[32mGET /api/books HTTP/1.1[0m" 308 -
2020/06/11 17:57:27 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 17:57:27] "[35m[1mGET /api/books/ HTTP/1.1[0m" 500 -
2020/06/11 18:00:49 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:01:21 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:01:21 root __init__.py[98] wrapped() ERROR: Error: Directory migrations already exists and is not empty
2020/06/11 18:01:46 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:02:19 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:03:19 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:04:12 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:04:12 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:04:17 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:04:17] "[32mGET /api/books HTTP/1.1[0m" 308 -
2020/06/11 18:04:18 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:04:18] "[37mGET /api/books/ HTTP/1.1[0m" 200 -
2020/06/11 18:04:25 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:04:25] "[32mGET /api/author HTTP/1.1[0m" 308 -
2020/06/11 18:04:25 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:04:25] "[37mGET /api/author/ HTTP/1.1[0m" 200 -
2020/06/11 18:04:37 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:04:37] "[35m[1mPOST /api/author HTTP/1.1[0m" 500 -
2020/06/11 18:04:48 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:04:48] "[37mPOST /api/author/ HTTP/1.1[0m" 201 -
2020/06/11 18:04:54 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:04:54] "[37mGET /api/author/ HTTP/1.1[0m" 200 -
2020/06/11 18:08:09 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:08:10 flask_api __init__.py[37] create_app() INFO: Flask Rest Api startup
2020/06/11 18:08:17 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:08:17] "[37mPOST /api/books/ HTTP/1.1[0m" 201 -
2020/06/11 18:08:39 werkzeug _internal.py[113] _log() INFO: 127.0.0.1 - - [11/Jun/2020 18:08:39] "[37mGET /api/books/ HTTP/1.1[0m" 200 -
